### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by purplefish32** [JoshuaEstes/ServerTools#8]
Hello, 
I am often getting tmeouts using ServerTools :

```
[RuntimeException]      
The process timed out
```

Is there any way to fix this ?

**Comment by JoshuaEstes** [comment]
what task are you running?

**Comment by purplefish32** [comment]
st sf2:init , and another that I have making : sf wordpress:init (For the moment only does a git clone of the wordpress repo on github)

**Comment by JoshuaEstes** [comment]
Been wanting to make one for wordpress, drupal, and magento, but haven't had the time yet.

What command is it executing when it gets the timeout? I have run into an issue every now and again when it's running composer.phar install

**Comment by purplefish32** [comment]
I would be more than happy to contribute to your project once I have finished my WordPress installer
I am also game on giving a hand for the Drupal installer (magneto not so much :))

**Comment by purplefish32** [comment]
here is the detail of what I have started : 
https://github.com/purplefish32/ServerTools/blob/develop/src/Wordpress/initCommand.php
I never get to ( Times out just before ) : 
    new Process('rm -rf .git/ .gitignore'),

**Comment by JoshuaEstes** [comment]
Can you do a manual?

```
git clone git://github.com/WordPress/WordPress.git .
```

**Comment by purplefish32** [comment]
Yeah allays have been, allthough Worpress is : 34.07 MiB and git reports a 251 KiB/s connection speed, so I guess I'm thrashing the 60s composer time out (see: https://github.com/composer/composer/pull/345)

**Comment by purplefish32** [comment]
https://github.com/purplefish32/composer/blob/master/doc/04-schema.md

"process-timeout: Defaults to 300. The duration processes like git clones can run before Composer assumes they died out. You may need to make this higher if you have a slow connection or huge vendors."

Not sure if this means installing composer from source an messing around with the timeout value or not.

**Comment by JoshuaEstes** [comment]
I actually had a few issues with this and found the cause for some of the issues. Here's some output from my console.

```
- Installing jms/aop-bundle (1.0.0)
  Downloading: 100%         

- Installing jms/metadata (1.1.1)
  Downloading: 100%         



[Composer\Downloader\TransportException]                                                         
The "http://nodeload.github.com/schmittjoh/metadata/zipball/1.1.1" file could not be downloaded  
```

I fixed this by adding repositories to the composer.json file like so:

```
....
},
"repositories": [
      {
          "type": "git",
          "url": "git://github.com/schmittjoh/metadata.git"
      },
      {
          "type": "git",
          "url": "git://github.com/schmittjoh/JMSSecurityExtraBundle.git"
      }
  ],
"require": {
....
```

There is also a way to increase the timeout for each process. I'll push an update shortly that should increase the timeout for the composer.phar install process. I also want to bring this to the sf2 community's attention as I think that the repos should go into the composer.json file to avoid stuff like this.

**Comment by JoshuaEstes** [comment]
https://github.com/JoshuaEstes/ServerTools/commit/982e684ca331bcabb372b5053a1dfb089bc99df5

That should fix the timeout on slow connections, but if it cannot connect to where it downloads then there is really nothing else I can do.

**Comment by purplefish32** [comment]
Looking into this once again it hit me : 
This bug has nothing to do with composer :)
This is just a process timeout : 

```
 public function __construct($commandline, $cwd = null, array $env = null, $stdin = null, $timeout = 60, array $options = array())
```

Changed my code to : 

```
 new Process('git clone git://github.com/WordPress/WordPress.git .', null, null, null, 300),
```

Works mutch better
